# Generated by Django 2.2.16 on 2023-01-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('id',), 'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
